Header header
float64 des_p_x
float64 des_p_y
float64 des_p_z

float64 des_v_x
float64 des_v_y
float64 des_v_z

float64 des_a_x
float64 des_a_y
float64 des_a_z

float64 des_bodyrate_x
float64 des_bodyrate_y
float64 des_bodyrate_z


float64 des_q_x
float64 des_q_y
float64 des_q_z
float64 des_q_w

float64 sim_des_q_x
float64 sim_des_q_y
float64 sim_des_q_z
float64 sim_des_q_w


float64 des_thr
float64 thr2acc
float64 hover_percentage
float64 thr_scale_compensate
float64 voltage

float64 odom_v_x
float64 odom_v_y
float64 odom_v_z

float64 odom_p_x
float64 odom_p_y
float64 odom_p_z

float64 des_br_x
float64 des_br_y
float64 des_br_z

float64 d_acc_x
float64 d_acc_y
float64 d_acc_z

float64 d_br_x
float64 d_br_y
float64 d_br_z

float64 cmd_q_x
float64 cmd_q_y
float64 cmd_q_z
float64 cmd_q_w

float64 imu_q_x
float64 imu_q_y
float64 imu_q_z
float64 imu_q_w

float64 cmd_v_x
float64 cmd_v_y
float64 cmd_v_z
float64 des_yaw

float64 T_x
float64 T_y
float64 T_z

float64 T_roll
float64 T_pitch
float64 T_yaw

float64 Tdot_x
float64 Tdot_y
float64 Tdot_z

float64 Tdot_roll
float64 Tdot_pitch
float64 Tdot_yaw
